---
name: Auto-Approve and Auto-Merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve-merge-dependabot:
    uses: Neovici/cfg/.github/workflows/auto-approve-merge-dependabot.yml@master
    secrets: inherit
