---
name: Github CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install
      run: npm ci

    - name: Lint commits
      uses: wagoid/commitlint-github-action@v5

    - name: ESLint
      run: npm run lint

    - name: Test and report
      env:
        CC_TEST_REPORTER_ID: a57ca5e66cf9c10852daa735ad4d4eed3dd49e61af2a44768fa73cda1736ceab
        GIT_BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || github.ref }}
        GIT_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        NEO_CC_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        NEO_CC: ./cc-test-reporter
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: |
        ([[ -e $NEO_CC ]] || curl -L $NEO_CC_URL > $NEO_CC) && chmod +x $NEO_CC
        $NEO_CC before-build
        echo "::add-matcher::.github/karma-problem-matcher.json"
        npm test
        $NEO_CC after-build --exit-code $?

    - name: Semantic release
      run: npx semantic-release
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
